@startuml

title 画面遷移図

トップ: /
登録: /register
ログイン: /login
募集: /recruit
参加: /join
プロフィール: /profile/:id
ランキング: /ranking
キャラクターセレクト: /character-select
ルール: /rule
"参加:非公開": /join/private
"参加:公開": /join/public
"プロフィール:編集": /profile/edit
ランク一覧: /rank
ゲーム: /gohome
404: /<not_exists_path>

[*] --> トップ
登録 -> トップ
トップ -> 登録
ログイン -> トップ
トップ -> ログイン
ログアウト -> トップ
トップ -> ログアウト

トップ --> 募集
トップ --> 参加
トップ --> プロフィール
トップ --> ランキング
トップ --> キャラクターセレクト
トップ --> ルール

募集 ---> ゲーム

参加 --> 参加:非公開
参加 --> 参加:公開

プロフィール --> プロフィール:編集
プロフィール --> ランク一覧

参加:非公開 --> ゲーム
参加:公開 --> ゲーム

@enduml