@startuml
title ゲーム中の状態遷移

[*] --> うさぎさんターン : ゲーム開始

うさぎさんターン -> ポーズ画面 : ポーズボタン押下
ポーズ画面 -> うさぎさんターン : さいかいボタン押下

ばいきんくんターン -> ポーズ画面 : ポーズボタン押下
ポーズ画面 -> ばいきんくんターン : さいかいボタン押下

ポーズ画面 : さいかい
ポーズ画面 : やめる

うさぎさんターン -[hidden]ri-> ポーズ画面

state うさぎさんターン {
    state "単語選択" as pws
    state "単語選択確認" as pwsc
    state "うさぎさん移動" as pm

    pwsc : よい
    pwsc : よくない

    [*] -> pws
    pwsc -> pws : よくないボタン選択
    pwsc -> pm : よいボタン選択
    pws -> pwsc : 単語選択

    [*] -> pm : 制限時間経過
    pm -> [*]

    [*] -[hidden]-> pws
    pws -[hidden]-> pwsc
    pwsc -[hidden]-> pm
    pm -[hidden]->[*]
}


うさぎさんターン -> 勝敗判定
勝敗判定 -> ばいきんくんターン 
うさぎさんターン -[hidden]-> 勝敗判定
勝敗判定 -[hidden]-> ばいきんくんターン

勝敗判定 : うさぎさんがおうちにたどり着いたか
勝敗判定 : ばいきんくんとうさぎさんが濃厚接触したか

state ばいきんくんターン {
    state "単語選択" as bws
    state "単語選択確認" as bwsc
    state "ばいきんくん移動" as bm

    bwsc : よい
    bwsc : よくない

    [*] -> bws
    bwsc -> bws : よくないボタン選択
    bwsc -> bm : よいボタン選択
    bws -> bwsc : 単語選択

    [*] -> bm : 制限時間経過
    bm -> [*]

    [*] -[hidden]-> bws
    bws -[hidden]-> bwsc
    bwsc -[hidden]-> bm
    bm -[hidden]->[*]
}

ばいきんくんターン -> 勝敗判定
勝敗判定 -> うさぎさんターン

勝敗判定 -> [*] : ゲーム終了
勝敗判定 -[hidden]-> [*]

うさぎさんターン -> [*] : 切断検知
ばいきんくんターン -> [*] : 切断検知

@enduml
